// DO NOT EDIT
// Generated by JFlex 1.9.1 http://jflex.de/
// source: org/zaproxy/zap/extension/httppanel/view/syntaxhighlight/lexers/HttpResponseHeaderTokenMaker.flex
/*
 * This file is based on the flex files from RSyntaxTextArea.
 *
 * HttpResponseHeaderTokenMaker.flex - Tokenises the status line and headers of an
 * HTTP response.  Used as a delegate by HttpResponseTokenMaker.
 *
 * IMPORTANT: RSyntaxTextArea calls getTokenList() ONE LINE AT A TIME.
 * State across lines is communicated via the initialTokenType parameter and addEndToken().
 * All internal token types are negative so that WrappedSyntaxView.isPaintable() returns
 * false for them, preventing BadLocationException during mouse drag selection.
 *
 * Internal token type → meaning:
 *   INTERNAL_HEADER_NAME       → next line is a header name; body type not yet known
 *   INTERNAL_HEADER_NAME_HTML  → next line is a header name; HTML body detected
 *   INTERNAL_HEADER_NAME_JS    → next line is a header name; JavaScript body detected
 *   INTERNAL_HEADER_NAME_JSON  → next line is a header name; JSON body detected
 *   INTERNAL_HEADER_NAME_XML   → next line is a header name; XML body detected
 *   INTERNAL_HEADER_VALUE      → continuation of a header value; body type not yet known
 *   INTERNAL_HEADER_VALUE_HTML → continuation of a header value; HTML body detected
 *   INTERNAL_HEADER_VALUE_JS   → continuation of a header value; JavaScript body detected
 *   INTERNAL_HEADER_VALUE_JSON → continuation of a header value; JSON body detected
 *   INTERNAL_HEADER_VALUE_XML  → continuation of a header value; XML body detected
 *   INTERNAL_HEADER_VALUE_CT   → continuation of a Content-Type header value
 *
 * On the blank line that separates headers from body, the EOF action emits one of:
 *   SIGNAL_BODY_PLAIN → body should be rendered as plain text
 *   SIGNAL_BODY_HTML  → body should be rendered as HTML
 *   SIGNAL_BODY_JS    → body should be rendered as JavaScript
 *   SIGNAL_BODY_JSON  → body should be rendered as JSON
 *   SIGNAL_BODY_XML   → body should be rendered as XML
 */
package org.zaproxy.zap.extension.httppanel.view.syntaxhighlight.lexers;

import javax.swing.text.Segment;
import org.fife.ui.rsyntaxtextarea.Token;
import org.fife.ui.rsyntaxtextarea.AbstractJFlexTokenMaker;

@SuppressWarnings("fallthrough")
public class HttpResponseHeaderTokenMaker extends AbstractJFlexTokenMaker {

    /**
     * This character denotes the end of file.
     */
    public static final int YYEOF = -1;

    // Lexical states.
    public static final int YYINITIAL = 0;

    public static final int HEADER_NAME = 2;

    public static final int HEADER_NAME_CONTENT_TYPE = 4;

    public static final int HEADER_VALUE = 6;

    public static final int HEADER_VALUE_CONTENT_TYPE = 8;

    /**
     * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
     * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
     *                  at the beginning of a line
     * l is of the form l = 2*k, k a non negative integer
     */
    private static final int[] ZZ_LEXSTATE = { 0, 0, 1, 1, 2, 2, 3, 3, 4, 4 };

    /**
     * Top-level table for translating characters to character classes
     */
    private static final int[] ZZ_CMAP_TOP = zzUnpackcmap_top();

    private static final String ZZ_CMAP_TOP_PACKED_0 = "\1\0\u10ff\u0100";

    private static int[] zzUnpackcmap_top() {
        int[] result = new int[4352];
        int offset = 0;
        offset = zzUnpackcmap_top(ZZ_CMAP_TOP_PACKED_0, offset, result);
        return result;
    }

    private static int zzUnpackcmap_top(String packed, int offset, int[] result) {
        int i = 0;
        /* index in packed string  */
        int j = offset;
        /* index in unpacked array */
        int l = packed.length();
        while (i < l) {
            int count = packed.charAt(i++);
            int value = packed.charAt(i++);
            do result[j++] = value; while (--count > 0);
        }
        return j;
    }

    /**
     * Second-level tables for translating characters to character classes
     */
    private static final int[] ZZ_CMAP_BLOCKS = zzUnpackcmap_blocks();

    private static final String ZZ_CMAP_BLOCKS_PACKED_0 = "\11\0\1\1\1\2\2\0\1\2\22\0\1\1\14\0" + "\1\3\1\4\1\5\12\6\1\7\6\0\7\10\1\11" + "\7\10\1\12\3\10\1\13\6\10\6\0\32\10\u0185\0";

    private static int[] zzUnpackcmap_blocks() {
        int[] result = new int[512];
        int offset = 0;
        offset = zzUnpackcmap_blocks(ZZ_CMAP_BLOCKS_PACKED_0, offset, result);
        return result;
    }

    private static int zzUnpackcmap_blocks(String packed, int offset, int[] result) {
        int i = 0;
        /* index in packed string  */
        int j = offset;
        /* index in unpacked array */
        int l = packed.length();
        while (i < l) {
            int count = packed.charAt(i++);
            int value = packed.charAt(i++);
            do result[j++] = value; while (--count > 0);
        }
        return j;
    }

    /**
     * Translates DFA states to action switch labels.
     */
    private static final int[] ZZ_ACTION = zzUnpackAction();

    private static final String ZZ_ACTION_PACKED_0 = "\5\0\1\1\1\2\2\1\1\3\1\2\1\4\1\5" + "\1\3\1\6\1\7\1\10\2\1\1\11\3\1\1\12" + "\1\1\1\12";

    private static int[] zzUnpackAction() {
        int[] result = new int[26];
        int offset = 0;
        offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
        return result;
    }

    private static int zzUnpackAction(String packed, int offset, int[] result) {
        int i = 0;
        /* index in packed string  */
        int j = offset;
        /* index in unpacked array */
        int l = packed.length();
        while (i < l) {
            int count = packed.charAt(i++);
            int value = packed.charAt(i++);
            do result[j++] = value; while (--count > 0);
        }
        return j;
    }

    /**
     * Translates a state to a row index in the transition table
     */
    private static final int[] ZZ_ROWMAP = zzUnpackRowMap();

    private static final String ZZ_ROWMAP_PACKED_0 = "\0\0\0\14\0\30\0\44\0\60\0\74\0\110\0\124" + "\0\140\0\154\0\170\0\204\0\220\0\204\0\204\0\234" + "\0\250\0\264\0\300\0\74\0\314\0\330\0\344\0\360" + "\0\374\0\74";

    private static int[] zzUnpackRowMap() {
        int[] result = new int[26];
        int offset = 0;
        offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
        return result;
    }

    private static int zzUnpackRowMap(String packed, int offset, int[] result) {
        int i = 0;
        /* index in packed string  */
        int j = offset;
        /* index in unpacked array */
        int l = packed.length() - 1;
        while (i < l) {
            int high = packed.charAt(i++) << 16;
            result[j++] = high | packed.charAt(i++);
        }
        return j;
    }

    /**
     * The transition table of the DFA
     */
    private static final int[] ZZ_TRANS = zzUnpacktrans();

    private static final String ZZ_TRANS_PACKED_0 = "\1\6\1\7\1\0\3\6\1\10\2\6\1\11\2\6" + "\1\12\1\13\1\0\4\12\1\14\4\15\1\16\1\7" + "\1\0\4\16\1\17\4\16\1\20\1\7\1\0\11\20" + "\1\21\1\7\1\0\11\21\1\6\2\0\11\6\1\0" + "\1\7\12\0\1\6\2\0\3\6\1\22\6\6\2\0" + "\10\6\1\23\2\12\1\0\4\12\1\0\5\12\1\13" + "\1\0\4\12\1\0\4\12\14\0\2\12\1\0\1\15" + "\2\12\1\15\1\0\4\15\2\20\1\0\11\20\2\21" + "\1\0\11\21\1\6\2\0\3\6\1\24\6\6\2\0" + "\10\6\1\25\1\6\2\0\7\6\1\26\2\6\2\0" + "\2\6\1\27\7\6\2\0\3\6\1\30\6\6\2\0" + "\1\6\1\31\10\6\2\0\3\6\1\32\5\6";

    private static int[] zzUnpacktrans() {
        int[] result = new int[264];
        int offset = 0;
        offset = zzUnpacktrans(ZZ_TRANS_PACKED_0, offset, result);
        return result;
    }

    private static int zzUnpacktrans(String packed, int offset, int[] result) {
        int i = 0;
        /* index in packed string  */
        int j = offset;
        /* index in unpacked array */
        int l = packed.length();
        while (i < l) {
            int count = packed.charAt(i++);
            int value = packed.charAt(i++);
            value--;
            do result[j++] = value; while (--count > 0);
        }
        return j;
    }

    /**
     * Error code for "Unknown internal scanner error".
     */
    private static final int ZZ_UNKNOWN_ERROR = 0;

    /**
     * Error code for "could not match input".
     */
    private static final int ZZ_NO_MATCH = 1;

    /**
     * Error code for "pushback value was too large".
     */
    private static final int ZZ_PUSHBACK_2BIG = 2;

    /**
     * Error messages for {@link #ZZ_UNKNOWN_ERROR}, {@link #ZZ_NO_MATCH}, and
     * {@link #ZZ_PUSHBACK_2BIG} respectively.
     */
    private static final String[] ZZ_ERROR_MSG = { "Unknown internal scanner error", "Error: could not match input", "Error: pushback value was too large" };

    /**
     * ZZ_ATTRIBUTE[aState] contains the attributes of state {@code aState}
     */
    private static final int[] ZZ_ATTRIBUTE = zzUnpackAttribute();

    private static final String ZZ_ATTRIBUTE_PACKED_0 = "\5\0\6\1\1\11\1\1\2\11\13\1";

    private static int[] zzUnpackAttribute() {
        int[] result = new int[26];
        int offset = 0;
        offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
        return result;
    }

    private static int zzUnpackAttribute(String packed, int offset, int[] result) {
        int i = 0;
        /* index in packed string  */
        int j = offset;
        /* index in unpacked array */
        int l = packed.length();
        while (i < l) {
            int count = packed.charAt(i++);
            int value = packed.charAt(i++);
            do result[j++] = value; while (--count > 0);
        }
        return j;
    }

    /**
     * Input device.
     */
    private java.io.Reader zzReader;

    /**
     * Current state of the DFA.
     */
    private int zzState;

    /**
     * Current lexical state.
     */
    private int zzLexicalState = YYINITIAL;

    /**
     * This buffer contains the current text to be matched and is the source of the {@link #yytext()}
     * string.
     */
    private char[] zzBuffer;

    /**
     * Text position at the last accepting state.
     */
    private int zzMarkedPos;

    /**
     * Current text position in the buffer.
     */
    private int zzCurrentPos;

    /**
     * Marks the beginning of the {@link #yytext()} string in the buffer.
     */
    private int zzStartRead;

    /**
     * Marks the last character in the buffer, that has been read from input.
     */
    private int zzEndRead;

    /**
     * Whether the scanner is at the end of file.
     * @see #yyatEOF
     */
    private boolean zzAtEOF;

    /**
     * The number of occupied positions in {@link #zzBuffer} beyond {@link #zzEndRead}.
     *
     * <p>When a lead/high surrogate has been read from the input stream into the final
     * {@link #zzBuffer} position, this will have a value of 1; otherwise, it will have a value of 0.
     */
    private int zzFinalHighSurrogate = 0;

    /**
     * Number of newlines encountered up to the start of the matched text.
     */
    @SuppressWarnings("unused")
    private int yyline;

    /**
     * Number of characters from the last newline up to the start of the matched text.
     */
    @SuppressWarnings("unused")
    private int yycolumn;

    /**
     * Number of characters up to the start of the matched text.
     */
    @SuppressWarnings("unused")
    private long yychar;

    /**
     * Whether the scanner is currently at the beginning of a line.
     */
    @SuppressWarnings("unused")
    private boolean zzAtBOL = true;

    /**
     * Whether the user-EOF-code has already been executed.
     */
    @SuppressWarnings("unused")
    private boolean zzEOFDone;

    /* user code: */
    /* ------------------------------------------------------------------ */
    /* Internal (negative) token types — cross-line state                  */
    /* ------------------------------------------------------------------ */
    static final int INTERNAL_HEADER_NAME = -1;

    static final int INTERNAL_HEADER_NAME_HTML = -2;

    static final int INTERNAL_HEADER_NAME_JS = -3;

    static final int INTERNAL_HEADER_NAME_JSON = -4;

    static final int INTERNAL_HEADER_NAME_XML = -5;

    static final int INTERNAL_HEADER_VALUE = -6;

    static final int INTERNAL_HEADER_VALUE_HTML = -7;

    static final int INTERNAL_HEADER_VALUE_JS = -8;

    static final int INTERNAL_HEADER_VALUE_JSON = -9;

    static final int INTERNAL_HEADER_VALUE_XML = -10;

    static final int INTERNAL_HEADER_VALUE_CT = -11;

    /* ------------------------------------------------------------------ */
    /* Signal tokens emitted on the blank header/body separator line.      */
    /* Consumed by HttpResponseTokenMaker to select the body token maker.  */
    /* ------------------------------------------------------------------ */
    static final int SIGNAL_BODY_PLAIN = -20;

    static final int SIGNAL_BODY_HTML = -21;

    static final int SIGNAL_BODY_JS = -22;

    static final int SIGNAL_BODY_JSON = -23;

    static final int SIGNAL_BODY_XML = -24;

    /**
     * Body type detected from Content-Type; carried as instance state only
     *  within a single yylex() call (reset at the top of getTokenList).
     */
    private int bodySignal = SIGNAL_BODY_PLAIN;

    private void addEndToken(int tokenType) {
        addToken(zzMarkedPos, zzMarkedPos, tokenType);
    }

    private void addToken(int tokenType) {
        addToken(zzStartRead, zzMarkedPos - 1, tokenType);
    }

    private void addToken(int start, int end, int tokenType) {
        int so = start + offsetShift;
        addToken(zzBuffer, start, end, tokenType, so);
    }

    @Override
    public void addToken(char[] array, int start, int end, int tokenType, int startOffset) {
        super.addToken(array, start, end, tokenType, startOffset);
        zzStartRead = zzMarkedPos;
    }

    /**
     * Returns the internal type for "still in header name" with the current body signal.
     */
    private int headerNameType() {
        switch(bodySignal) {
            case SIGNAL_BODY_HTML:
                return INTERNAL_HEADER_NAME_HTML;
            case SIGNAL_BODY_JS:
                return INTERNAL_HEADER_NAME_JS;
            case SIGNAL_BODY_JSON:
                return INTERNAL_HEADER_NAME_JSON;
            case SIGNAL_BODY_XML:
                return INTERNAL_HEADER_NAME_XML;
            default:
                return INTERNAL_HEADER_NAME;
        }
    }

    /**
     * Returns the internal type for "still in header value" with the current body signal.
     */
    private int headerValueType() {
        switch(bodySignal) {
            case SIGNAL_BODY_HTML:
                return INTERNAL_HEADER_VALUE_HTML;
            case SIGNAL_BODY_JS:
                return INTERNAL_HEADER_VALUE_JS;
            case SIGNAL_BODY_JSON:
                return INTERNAL_HEADER_VALUE_JSON;
            case SIGNAL_BODY_XML:
                return INTERNAL_HEADER_VALUE_XML;
            default:
                return INTERNAL_HEADER_VALUE;
        }
    }

    @Override
    public Token getTokenList(Segment text, int initialTokenType, int startOffset) {
        resetTokenList();
        this.offsetShift = -text.offset + startOffset;
        bodySignal = SIGNAL_BODY_PLAIN;
        s = text;
        yyreset(zzReader);
        switch(initialTokenType) {
            case INTERNAL_HEADER_NAME:
                yybegin(HEADER_NAME);
                break;
            case INTERNAL_HEADER_NAME_HTML:
                bodySignal = SIGNAL_BODY_HTML;
                yybegin(HEADER_NAME);
                break;
            case INTERNAL_HEADER_NAME_JS:
                bodySignal = SIGNAL_BODY_JS;
                yybegin(HEADER_NAME);
                break;
            case INTERNAL_HEADER_NAME_JSON:
                bodySignal = SIGNAL_BODY_JSON;
                yybegin(HEADER_NAME);
                break;
            case INTERNAL_HEADER_NAME_XML:
                bodySignal = SIGNAL_BODY_XML;
                yybegin(HEADER_NAME);
                break;
            case INTERNAL_HEADER_VALUE:
                yybegin(HEADER_VALUE);
                break;
            case INTERNAL_HEADER_VALUE_HTML:
                bodySignal = SIGNAL_BODY_HTML;
                yybegin(HEADER_VALUE);
                break;
            case INTERNAL_HEADER_VALUE_JS:
                bodySignal = SIGNAL_BODY_JS;
                yybegin(HEADER_VALUE);
                break;
            case INTERNAL_HEADER_VALUE_JSON:
                bodySignal = SIGNAL_BODY_JSON;
                yybegin(HEADER_VALUE);
                break;
            case INTERNAL_HEADER_VALUE_XML:
                bodySignal = SIGNAL_BODY_XML;
                yybegin(HEADER_VALUE);
                break;
            case INTERNAL_HEADER_VALUE_CT:
                yybegin(HEADER_VALUE_CONTENT_TYPE);
                break;
            default:
                yybegin(YYINITIAL);
                break;
        }
        return yylex();
    }

    private boolean zzRefill() {
        return zzCurrentPos >= s.offset + s.count;
    }

    public final void yyreset(java.io.Reader reader) {
        zzBuffer = s.array;
        zzStartRead = s.offset;
        zzEndRead = zzStartRead + s.count;
        zzCurrentPos = zzMarkedPos = s.offset;
        zzLexicalState = YYINITIAL;
        zzReader = reader;
        zzAtBOL = true;
        zzAtEOF = false;
        zzEOFDone = false;
        zzFinalHighSurrogate = zzCurrentPos;
    }

    /**
     * Creates a new scanner
     *
     * @param   in  the java.io.Reader to read input from.
     */
    public HttpResponseHeaderTokenMaker(java.io.Reader in) {
        this.zzReader = in;
    }

    /**
     * Returns the maximum size of the scanner buffer, which limits the size of tokens.
     */
    private int zzMaxBufferLen() {
        return Integer.MAX_VALUE;
    }

    /**
     *  Whether the scanner buffer can grow to accommodate a larger token.
     */
    private boolean zzCanGrow() {
        return true;
    }

    /**
     * Translates raw input code points to DFA table row
     */
    private static int zzCMap(int input) {
        int offset = input & 255;
        return offset == input ? ZZ_CMAP_BLOCKS[offset] : ZZ_CMAP_BLOCKS[ZZ_CMAP_TOP[input >> 8] | offset];
    }

    /**
     * Closes the input reader.
     *
     * @throws java.io.IOException if the reader could not be closed.
     */
    @Override
    public final void yyclose() throws java.io.IOException {
        // indicate end of file
        zzAtEOF = true;
        // invalidate buffer
        zzEndRead = zzStartRead;
        if (zzReader != null) {
            zzReader.close();
        }
    }

    /**
     * Returns whether the scanner has reached the end of the reader it reads from.
     *
     * @return whether the scanner has reached EOF.
     */
    public final boolean yyatEOF() {
        return zzAtEOF;
    }

    /**
     * Returns the current lexical state.
     *
     * @return the current lexical state.
     */
    @Override
    public final int yystate() {
        return zzLexicalState;
    }

    /**
     * Enters a new lexical state.
     *
     * @param newState the new lexical state
     */
    @Override
    public final void yybegin(int newState) {
        zzLexicalState = newState;
    }

    /**
     * Returns the text matched by the current regular expression.
     *
     * @return the matched text.
     */
    @Override
    public final String yytext() {
        return new String(zzBuffer, zzStartRead, zzMarkedPos - zzStartRead);
    }

    /**
     * Returns the character at the given position from the matched text.
     *
     * <p>It is equivalent to {@code yytext().charAt(pos)}, but faster.
     *
     * @param position the position of the character to fetch. A value from 0 to {@code yylength()-1}.
     *
     * @return the character at {@code position}.
     */
    @Override
    public final char yycharat(int position) {
        return zzBuffer[zzStartRead + position];
    }

    /**
     * How many characters were matched.
     *
     * @return the length of the matched text region.
     */
    @Override
    public final int yylength() {
        return zzMarkedPos - zzStartRead;
    }

    /**
     * Reports an error that occurred while scanning.
     *
     * <p>In a well-formed scanner (no or only correct usage of {@code yypushback(int)} and a
     * match-all fallback rule) this method will only be called with things that
     * "Can't Possibly Happen".
     *
     * <p>If this method is called, something is seriously wrong (e.g. a JFlex bug producing a faulty
     * scanner etc.).
     *
     * <p>Usual syntax/scanner level error handling should be done in error fallback rules.
     *
     * @param errorCode the code of the error message to display.
     */
    private static void zzScanError(int errorCode) {
        String message;
        try {
            message = ZZ_ERROR_MSG[errorCode];
        } catch (ArrayIndexOutOfBoundsException e) {
            message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
        }
        throw new Error(message);
    }

    /**
     * Pushes the specified amount of characters back into the input stream.
     *
     * <p>They will be read again by then next call of the scanning method.
     *
     * @param number the number of characters to be read again. This number must not be greater than
     *     {@link #yylength()}.
     */
    @Override
    public void yypushback(int number) {
        if (number > yylength())
            zzScanError(ZZ_PUSHBACK_2BIG);
        zzMarkedPos -= number;
    }

    /**
     * Resumes scanning until the next regular expression is matched, the end of input is encountered
     * or an I/O-Error occurs.
     *
     * @return the next token.
     */
    @SuppressWarnings("fallthrough")
    public Token yylex() {
        int zzInput;
        int zzAction;
        // cached fields:
        int zzCurrentPosL;
        int zzMarkedPosL;
        int zzEndReadL = zzEndRead;
        char[] zzBufferL = zzBuffer;
        int[] zzTransL = ZZ_TRANS;
        int[] zzRowMapL = ZZ_ROWMAP;
        int[] zzAttrL = ZZ_ATTRIBUTE;
        while (true) {
            zzMarkedPosL = zzMarkedPos;
            zzAction = -1;
            zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
            zzState = ZZ_LEXSTATE[zzLexicalState];
            // set up zzAction for empty match case:
            int zzAttributes = zzAttrL[zzState];
            if ((zzAttributes & 1) == 1) {
                zzAction = zzState;
            }
            zzForAction: {
                while (true) {
                    if (zzCurrentPosL < zzEndReadL) {
                        zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
                        zzCurrentPosL += Character.charCount(zzInput);
                    } else if (zzAtEOF) {
                        zzInput = YYEOF;
                        break zzForAction;
                    } else {
                        // store back cached positions
                        zzCurrentPos = zzCurrentPosL;
                        zzMarkedPos = zzMarkedPosL;
                        boolean eof = zzRefill();
                        // get translated positions and possibly new buffer
                        zzCurrentPosL = zzCurrentPos;
                        zzMarkedPosL = zzMarkedPos;
                        zzBufferL = zzBuffer;
                        zzEndReadL = zzEndRead;
                        if (eof) {
                            zzInput = YYEOF;
                            break zzForAction;
                        } else {
                            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
                            zzCurrentPosL += Character.charCount(zzInput);
                        }
                    }
                    int zzNext = zzTransL[zzRowMapL[zzState] + zzCMap(zzInput)];
                    if (zzNext == -1)
                        break zzForAction;
                    zzState = zzNext;
                    zzAttributes = zzAttrL[zzState];
                    if ((zzAttributes & 1) == 1) {
                        zzAction = zzState;
                        zzMarkedPosL = zzCurrentPosL;
                        if ((zzAttributes & 8) == 8)
                            break zzForAction;
                    }
                }
            }
            // store back cached position
            zzMarkedPos = zzMarkedPosL;
            if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
                zzAtEOF = true;
                switch(zzLexicalState) {
                    case YYINITIAL:
                        {
                            addEndToken(INTERNAL_HEADER_NAME);
                            return firstToken;
                        }
                    // fall though
                    case 27:
                        break;
                    case HEADER_NAME:
                        {
                            if (zzStartRead == zzEndRead) {
                                addEndToken(bodySignal);
                            } else {
                                addEndToken(headerNameType());
                            }
                            return firstToken;
                        }
                    // fall though
                    case 28:
                        break;
                    case HEADER_NAME_CONTENT_TYPE:
                        {
                            addEndToken(headerNameType());
                            return firstToken;
                        }
                    // fall though
                    case 29:
                        break;
                    case HEADER_VALUE:
                        {
                            addEndToken(headerNameType());
                            return firstToken;
                        }
                    // fall though
                    case 30:
                        break;
                    case HEADER_VALUE_CONTENT_TYPE:
                        {
                            addEndToken(headerNameType());
                            return firstToken;
                        }
                    // fall though
                    case 31:
                        break;
                    default:
                        return null;
                }
            } else {
                switch(zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
                    case 1:
                        {
                            addToken(Token.FUNCTION);
                        }
                    // fall through
                    case 11:
                        break;
                    case 2:
                        {
                            addToken(Token.WHITESPACE);
                        }
                    // fall through
                    case 12:
                        break;
                    case 3:
                        {
                            addToken(Token.DATA_TYPE);
                        }
                    // fall through
                    case 13:
                        break;
                    case 4:
                        {
                            addToken(Token.SEPARATOR);
                            yybegin(HEADER_VALUE);
                        }
                    // fall through
                    case 14:
                        break;
                    case 5:
                        {
                            String name = new String(zzBuffer, zzStartRead, zzMarkedPos - zzStartRead);
                            addToken(Token.DATA_TYPE);
                            if (name.equalsIgnoreCase("Content-Type")) {
                                yybegin(HEADER_NAME_CONTENT_TYPE);
                            }
                        }
                    // fall through
                    case 15:
                        break;
                    case 6:
                        {
                            addToken(Token.SEPARATOR);
                            yybegin(HEADER_VALUE_CONTENT_TYPE);
                        }
                    // fall through
                    case 16:
                        break;
                    case 7:
                        {
                            addToken(Token.LITERAL_CHAR);
                        }
                    // fall through
                    case 17:
                        break;
                    case 8:
                        {
                            String value = new String(zzBuffer, zzStartRead, zzMarkedPos - zzStartRead);
                            addToken(Token.LITERAL_CHAR);
                            if (value.regionMatches(true, 0, "application/json", 0, 16)) {
                                bodySignal = SIGNAL_BODY_JSON;
                            } else if (value.regionMatches(true, 0, "application/javascript", 0, 22) || value.regionMatches(true, 0, "text/javascript", 0, 15)) {
                                bodySignal = SIGNAL_BODY_JS;
                            } else if (value.regionMatches(true, 0, "text/html", 0, 9) || value.regionMatches(true, 0, "application/xhtml", 0, 17)) {
                                bodySignal = SIGNAL_BODY_HTML;
                            } else if (value.regionMatches(true, 0, "text/xml", 0, 8) || value.regionMatches(true, 0, "application/xml", 0, 15)) {
                                bodySignal = SIGNAL_BODY_XML;
                            }
                        }
                    // fall through
                    case 18:
                        break;
                    case 9:
                        {
                            addToken(Token.RESERVED_WORD);
                        }
                    // fall through
                    case 19:
                        break;
                    case 10:
                        {
                            addToken(Token.LITERAL_STRING_DOUBLE_QUOTE);
                        }
                    // fall through
                    case 20:
                        break;
                    default:
                        zzScanError(ZZ_NO_MATCH);
                }
            }
        }
    }

    public HttpResponseHeaderTokenMaker() {
    }
}
