// DO NOT EDIT
// Generated by JFlex 1.9.1 http://jflex.de/
// source:
// org/zaproxy/zap/extension/httppanel/view/syntaxhighlight/lexers/HttpRequestHeaderTokenMaker.flex
/*
 * This file is based on the flex files from RSyntaxTextArea.
 *
 * HttpRequestHeaderTokenMaker.flex - Tokenises the request line and headers of an
 * HTTP request.  Used as a delegate by HttpRequestTokenMaker.
 *
 * IMPORTANT: RSyntaxTextArea calls getTokenList() ONE LINE AT A TIME.
 * State across lines is communicated via the initialTokenType parameter and addEndToken().
 * All internal token types are negative so that WrappedSyntaxView.isPaintable() returns
 * false for them, preventing BadLocationException during mouse drag selection.
 *
 * Internal token type → meaning:
 *   INTERNAL_HEADER_NAME       → next line is a header name; body type not yet known
 *   INTERNAL_HEADER_NAME_FORM  → next line is a header name; form body detected
 *   INTERNAL_HEADER_NAME_JSON  → next line is a header name; JSON body detected
 *   INTERNAL_HEADER_VALUE      → continuation of a header value; body type not yet known
 *   INTERNAL_HEADER_VALUE_FORM → continuation of a header value; form body detected
 *   INTERNAL_HEADER_VALUE_JSON → continuation of a header value; JSON body detected
 *   INTERNAL_HEADER_VALUE_CT   → continuation of a Content-Type header value
 *
 * On the blank line that separates headers from body, the EOF action emits one of:
 *   SIGNAL_BODY_PLAIN → body should be rendered as plain text
 *   SIGNAL_BODY_FORM  → body should be rendered as form-urlencoded
 *   SIGNAL_BODY_JSON  → body should be rendered as JSON
 */
package org.zaproxy.zap.extension.httppanel.view.syntaxhighlight.lexers;

import javax.swing.text.Segment;
import org.fife.ui.rsyntaxtextarea.AbstractJFlexTokenMaker;
import org.fife.ui.rsyntaxtextarea.Token;

@SuppressWarnings("fallthrough")
public class HttpRequestHeaderTokenMaker extends AbstractJFlexTokenMaker {

    /** This character denotes the end of file. */
    public static final int YYEOF = -1;

    // Lexical states.
    public static final int YYINITIAL = 0;

    public static final int HEADER_NAME = 2;

    public static final int HEADER_NAME_CONTENT_TYPE = 4;

    public static final int HEADER_VALUE = 6;

    public static final int HEADER_VALUE_CONTENT_TYPE = 8;

    /**
     * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l ZZ_LEXSTATE[l+1] is the state
     * in the DFA for the lexical state l at the beginning of a line l is of the form l = 2*k, k a
     * non negative integer
     */
    private static final int[] ZZ_LEXSTATE = {0, 0, 1, 1, 2, 2, 3, 3, 4, 4};

    /** Top-level table for translating characters to character classes */
    private static final int[] ZZ_CMAP_TOP = zzUnpackcmap_top();

    private static final String ZZ_CMAP_TOP_PACKED_0 = "\1\0\u10ff\u0100";

    private static int[] zzUnpackcmap_top() {
        int[] result = new int[4352];
        int offset = 0;
        offset = zzUnpackcmap_top(ZZ_CMAP_TOP_PACKED_0, offset, result);
        return result;
    }

    private static int zzUnpackcmap_top(String packed, int offset, int[] result) {
        int i = 0;
        /* index in packed string  */
        int j = offset;
        /* index in unpacked array */
        int l = packed.length();
        while (i < l) {
            int count = packed.charAt(i++);
            int value = packed.charAt(i++);
            do result[j++] = value;
            while (--count > 0);
        }
        return j;
    }

    /** Second-level tables for translating characters to character classes */
    private static final int[] ZZ_CMAP_BLOCKS = zzUnpackcmap_blocks();

    private static final String ZZ_CMAP_BLOCKS_PACKED_0 =
            "\11\0\1\1\1\2\2\0\1\2\22\0\1\1\14\0"
                    + "\1\3\1\4\1\5\12\6\1\7\6\0\1\10\1\11"
                    + "\1\12\1\13\1\14\1\11\1\15\1\16\1\17\2\11"
                    + "\1\20\1\11\1\21\1\22\1\23\1\11\1\24\1\25"
                    + "\1\26\1\27\5\11\6\0\32\11\u0185\0";

    private static int[] zzUnpackcmap_blocks() {
        int[] result = new int[512];
        int offset = 0;
        offset = zzUnpackcmap_blocks(ZZ_CMAP_BLOCKS_PACKED_0, offset, result);
        return result;
    }

    private static int zzUnpackcmap_blocks(String packed, int offset, int[] result) {
        int i = 0;
        /* index in packed string  */
        int j = offset;
        /* index in unpacked array */
        int l = packed.length();
        while (i < l) {
            int count = packed.charAt(i++);
            int value = packed.charAt(i++);
            do result[j++] = value;
            while (--count > 0);
        }
        return j;
    }

    /** Translates DFA states to action switch labels. */
    private static final int[] ZZ_ACTION = zzUnpackAction();

    private static final String ZZ_ACTION_PACKED_0 =
            "\5\0\1\1\1\2\7\1\1\3\1\2\1\4\1\5"
                    + "\1\3\1\6\1\7\1\10\23\1\1\11\7\1\1\12"
                    + "\2\1\1\12";

    private static int[] zzUnpackAction() {
        int[] result = new int[53];
        int offset = 0;
        offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
        return result;
    }

    private static int zzUnpackAction(String packed, int offset, int[] result) {
        int i = 0;
        /* index in packed string  */
        int j = offset;
        /* index in unpacked array */
        int l = packed.length();
        while (i < l) {
            int count = packed.charAt(i++);
            int value = packed.charAt(i++);
            do result[j++] = value;
            while (--count > 0);
        }
        return j;
    }

    /** Translates a state to a row index in the transition table */
    private static final int[] ZZ_ROWMAP = zzUnpackRowMap();

    private static final String ZZ_ROWMAP_PACKED_0 =
            "\0\0\0\30\0\60\0\110\0\140\0\170\0\220\0\250"
                    + "\0\300\0\330\0\360\0\u0108\0\u0120\0\u0138\0\u0150\0\u0168"
                    + "\0\u0180\0\u0198\0\u0180\0\u0180\0\u01b0\0\u01c8\0\u01e0\0\u01f8"
                    + "\0\u0210\0\u0228\0\u0240\0\u0258\0\u0270\0\u0288\0\u02a0\0\u02b8"
                    + "\0\u02d0\0\u02e8\0\u0300\0\u0318\0\u0330\0\u0348\0\u0360\0\u0378"
                    + "\0\u0390\0\u0180\0\u03a8\0\u03c0\0\u03d8\0\u03f0\0\u0408\0\u0420"
                    + "\0\u0438\0\u0450\0\u0468\0\u0480\0\170";

    private static int[] zzUnpackRowMap() {
        int[] result = new int[53];
        int offset = 0;
        offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
        return result;
    }

    private static int zzUnpackRowMap(String packed, int offset, int[] result) {
        int i = 0;
        /* index in packed string  */
        int j = offset;
        /* index in unpacked array */
        int l = packed.length() - 1;
        while (i < l) {
            int high = packed.charAt(i++) << 16;
            result[j++] = high | packed.charAt(i++);
        }
        return j;
    }

    /** The transition table of the DFA */
    private static final int[] ZZ_TRANS = zzUnpacktrans();

    private static final String ZZ_TRANS_PACKED_0 =
            "\1\6\1\7\1\0\7\6\1\10\1\11\1\6\1\12"
                    + "\1\13\3\6\1\14\1\15\2\6\1\16\1\6\1\17"
                    + "\1\20\1\0\4\17\1\21\20\22\1\23\1\7\1\0"
                    + "\4\23\1\24\20\23\1\25\1\7\1\0\25\25\1\26"
                    + "\1\7\1\0\25\26\1\6\2\0\25\6\1\0\1\7"
                    + "\26\0\1\6\2\0\17\6\1\27\6\6\2\0\11\6"
                    + "\1\30\14\6\2\0\11\6\1\31\14\6\2\0\11\6"
                    + "\1\32\11\6\1\33\2\6\2\0\20\6\1\34\5\6"
                    + "\2\0\5\6\1\35\11\6\1\36\4\6\1\31\1\6"
                    + "\2\0\21\6\1\37\3\6\2\17\1\0\4\17\1\0"
                    + "\21\17\1\20\1\0\4\17\1\0\20\17\30\0\2\17"
                    + "\1\0\1\22\2\17\1\22\1\0\20\22\2\25\1\0"
                    + "\25\25\2\26\1\0\25\26\1\6\2\0\16\6\1\40"
                    + "\7\6\2\0\15\6\1\41\10\6\2\0\23\6\1\42"
                    + "\2\6\2\0\5\6\1\43\20\6\2\0\23\6\1\44"
                    + "\2\6\2\0\23\6\1\45\2\6\2\0\23\6\1\46"
                    + "\2\6\2\0\22\6\1\31\3\6\2\0\5\6\1\47"
                    + "\20\6\2\0\16\6\1\50\7\6\2\0\11\6\1\51"
                    + "\14\6\1\52\1\0\26\6\2\0\10\6\1\42\15\6"
                    + "\2\0\20\6\1\53\5\6\2\0\14\6\1\54\11\6"
                    + "\2\0\7\6\1\55\16\6\2\0\7\6\1\56\16\6"
                    + "\2\0\11\6\1\57\14\6\2\0\23\6\1\56\2\6"
                    + "\2\0\2\6\1\60\23\6\2\0\17\6\1\61\6\6"
                    + "\2\0\13\6\1\42\12\6\2\0\11\6\1\42\14\6"
                    + "\2\0\7\6\1\31\16\6\2\0\3\6\1\62\22\6"
                    + "\2\0\16\6\1\63\7\6\2\0\1\6\1\64\24\6"
                    + "\2\0\22\6\1\42\3\6\2\0\3\6\1\65\21\6";

    private static int[] zzUnpacktrans() {
        int[] result = new int[1176];
        int offset = 0;
        offset = zzUnpacktrans(ZZ_TRANS_PACKED_0, offset, result);
        return result;
    }

    private static int zzUnpacktrans(String packed, int offset, int[] result) {
        int i = 0;
        /* index in packed string  */
        int j = offset;
        /* index in unpacked array */
        int l = packed.length();
        while (i < l) {
            int count = packed.charAt(i++);
            int value = packed.charAt(i++);
            value--;
            do result[j++] = value;
            while (--count > 0);
        }
        return j;
    }

    /** Error code for "Unknown internal scanner error". */
    private static final int ZZ_UNKNOWN_ERROR = 0;

    /** Error code for "could not match input". */
    private static final int ZZ_NO_MATCH = 1;

    /** Error code for "pushback value was too large". */
    private static final int ZZ_PUSHBACK_2BIG = 2;

    /**
     * Error messages for {@link #ZZ_UNKNOWN_ERROR}, {@link #ZZ_NO_MATCH}, and {@link
     * #ZZ_PUSHBACK_2BIG} respectively.
     */
    private static final String[] ZZ_ERROR_MSG = {
        "Unknown internal scanner error",
        "Error: could not match input",
        "Error: pushback value was too large"
    };

    /** ZZ_ATTRIBUTE[aState] contains the attributes of state {@code aState} */
    private static final int[] ZZ_ATTRIBUTE = zzUnpackAttribute();

    private static final String ZZ_ATTRIBUTE_PACKED_0 = "\5\0\13\1\1\11\1\1\2\11\25\1\1\11\13\1";

    private static int[] zzUnpackAttribute() {
        int[] result = new int[53];
        int offset = 0;
        offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
        return result;
    }

    private static int zzUnpackAttribute(String packed, int offset, int[] result) {
        int i = 0;
        /* index in packed string  */
        int j = offset;
        /* index in unpacked array */
        int l = packed.length();
        while (i < l) {
            int count = packed.charAt(i++);
            int value = packed.charAt(i++);
            do result[j++] = value;
            while (--count > 0);
        }
        return j;
    }

    /** Input device. */
    private java.io.Reader zzReader;

    /** Current state of the DFA. */
    private int zzState;

    /** Current lexical state. */
    private int zzLexicalState = YYINITIAL;

    /**
     * This buffer contains the current text to be matched and is the source of the {@link
     * #yytext()} string.
     */
    private char[] zzBuffer;

    /** Text position at the last accepting state. */
    private int zzMarkedPos;

    /** Current text position in the buffer. */
    private int zzCurrentPos;

    /** Marks the beginning of the {@link #yytext()} string in the buffer. */
    private int zzStartRead;

    /** Marks the last character in the buffer, that has been read from input. */
    private int zzEndRead;

    /**
     * Whether the scanner is at the end of file.
     *
     * @see #yyatEOF
     */
    private boolean zzAtEOF;

    /**
     * The number of occupied positions in {@link #zzBuffer} beyond {@link #zzEndRead}.
     *
     * <p>When a lead/high surrogate has been read from the input stream into the final {@link
     * #zzBuffer} position, this will have a value of 1; otherwise, it will have a value of 0.
     */
    private int zzFinalHighSurrogate = 0;

    /** Number of newlines encountered up to the start of the matched text. */
    @SuppressWarnings("unused")
    private int yyline;

    /** Number of characters from the last newline up to the start of the matched text. */
    @SuppressWarnings("unused")
    private int yycolumn;

    /** Number of characters up to the start of the matched text. */
    @SuppressWarnings("unused")
    private long yychar;

    /** Whether the scanner is currently at the beginning of a line. */
    @SuppressWarnings("unused")
    private boolean zzAtBOL = true;

    /** Whether the user-EOF-code has already been executed. */
    @SuppressWarnings("unused")
    private boolean zzEOFDone;

    /* user code: */
    /* ------------------------------------------------------------------ */
    /* Internal (negative) token types — cross-line state                  */
    /* ------------------------------------------------------------------ */
    static final int INTERNAL_HEADER_NAME = -1;

    static final int INTERNAL_HEADER_NAME_FORM = -2;

    static final int INTERNAL_HEADER_NAME_JSON = -3;

    static final int INTERNAL_HEADER_VALUE = -4;

    static final int INTERNAL_HEADER_VALUE_FORM = -5;

    static final int INTERNAL_HEADER_VALUE_JSON = -6;

    static final int INTERNAL_HEADER_VALUE_CT = -7;

    /* ------------------------------------------------------------------ */
    /* Signal tokens emitted on the blank header/body separator line.      */
    /* Consumed by HttpRequestTokenMaker to select the body token maker.   */
    /* ------------------------------------------------------------------ */
    static final int SIGNAL_BODY_PLAIN = -10;

    static final int SIGNAL_BODY_FORM = -11;

    static final int SIGNAL_BODY_JSON = -12;

    /**
     * Body type detected from Content-Type; carried as instance state only within a single yylex()
     * call (reset at the top of getTokenList).
     */
    private int bodySignal = SIGNAL_BODY_PLAIN;

    private void addEndToken(int tokenType) {
        addToken(zzMarkedPos, zzMarkedPos, tokenType);
    }

    private void addToken(int tokenType) {
        addToken(zzStartRead, zzMarkedPos - 1, tokenType);
    }

    private void addToken(int start, int end, int tokenType) {
        int so = start + offsetShift;
        addToken(zzBuffer, start, end, tokenType, so);
    }

    @Override
    public void addToken(char[] array, int start, int end, int tokenType, int startOffset) {
        super.addToken(array, start, end, tokenType, startOffset);
        zzStartRead = zzMarkedPos;
    }

    /** Returns the internal type for "still in header name" with the current body signal. */
    private int headerNameType() {
        if (bodySignal == SIGNAL_BODY_FORM) return INTERNAL_HEADER_NAME_FORM;
        if (bodySignal == SIGNAL_BODY_JSON) return INTERNAL_HEADER_NAME_JSON;
        return INTERNAL_HEADER_NAME;
    }

    /** Returns the internal type for "still in header value" with the current body signal. */
    private int headerValueType() {
        if (bodySignal == SIGNAL_BODY_FORM) return INTERNAL_HEADER_VALUE_FORM;
        if (bodySignal == SIGNAL_BODY_JSON) return INTERNAL_HEADER_VALUE_JSON;
        return INTERNAL_HEADER_VALUE;
    }

    @Override
    public Token getTokenList(Segment text, int initialTokenType, int startOffset) {
        resetTokenList();
        this.offsetShift = -text.offset + startOffset;
        bodySignal = SIGNAL_BODY_PLAIN;
        s = text;
        yyreset(zzReader);
        switch (initialTokenType) {
            case INTERNAL_HEADER_NAME:
                yybegin(HEADER_NAME);
                break;
            case INTERNAL_HEADER_NAME_FORM:
                bodySignal = SIGNAL_BODY_FORM;
                yybegin(HEADER_NAME);
                break;
            case INTERNAL_HEADER_NAME_JSON:
                bodySignal = SIGNAL_BODY_JSON;
                yybegin(HEADER_NAME);
                break;
            case INTERNAL_HEADER_VALUE:
                yybegin(HEADER_VALUE);
                break;
            case INTERNAL_HEADER_VALUE_FORM:
                bodySignal = SIGNAL_BODY_FORM;
                yybegin(HEADER_VALUE);
                break;
            case INTERNAL_HEADER_VALUE_JSON:
                bodySignal = SIGNAL_BODY_JSON;
                yybegin(HEADER_VALUE);
                break;
            case INTERNAL_HEADER_VALUE_CT:
                yybegin(HEADER_VALUE_CONTENT_TYPE);
                break;
            default:
                yybegin(YYINITIAL);
                break;
        }
        return yylex();
    }

    private boolean zzRefill() {
        return zzCurrentPos >= s.offset + s.count;
    }

    public final void yyreset(java.io.Reader reader) {
        zzBuffer = s.array;
        zzStartRead = s.offset;
        zzEndRead = zzStartRead + s.count;
        zzCurrentPos = zzMarkedPos = s.offset;
        zzLexicalState = YYINITIAL;
        zzReader = reader;
        zzAtBOL = true;
        zzAtEOF = false;
        zzEOFDone = false;
        zzFinalHighSurrogate = zzCurrentPos;
    }

    /**
     * Creates a new scanner
     *
     * @param in the java.io.Reader to read input from.
     */
    public HttpRequestHeaderTokenMaker(java.io.Reader in) {
        this.zzReader = in;
    }

    /** Returns the maximum size of the scanner buffer, which limits the size of tokens. */
    private int zzMaxBufferLen() {
        return Integer.MAX_VALUE;
    }

    /** Whether the scanner buffer can grow to accommodate a larger token. */
    private boolean zzCanGrow() {
        return true;
    }

    /** Translates raw input code points to DFA table row */
    private static int zzCMap(int input) {
        int offset = input & 255;
        return offset == input
                ? ZZ_CMAP_BLOCKS[offset]
                : ZZ_CMAP_BLOCKS[ZZ_CMAP_TOP[input >> 8] | offset];
    }

    /**
     * Closes the input reader.
     *
     * @throws java.io.IOException if the reader could not be closed.
     */
    @Override
    public final void yyclose() throws java.io.IOException {
        // indicate end of file
        zzAtEOF = true;
        // invalidate buffer
        zzEndRead = zzStartRead;
        if (zzReader != null) {
            zzReader.close();
        }
    }

    /**
     * Returns whether the scanner has reached the end of the reader it reads from.
     *
     * @return whether the scanner has reached EOF.
     */
    public final boolean yyatEOF() {
        return zzAtEOF;
    }

    /**
     * Returns the current lexical state.
     *
     * @return the current lexical state.
     */
    @Override
    public final int yystate() {
        return zzLexicalState;
    }

    /**
     * Enters a new lexical state.
     *
     * @param newState the new lexical state
     */
    @Override
    public final void yybegin(int newState) {
        zzLexicalState = newState;
    }

    /**
     * Returns the text matched by the current regular expression.
     *
     * @return the matched text.
     */
    @Override
    public final String yytext() {
        return new String(zzBuffer, zzStartRead, zzMarkedPos - zzStartRead);
    }

    /**
     * Returns the character at the given position from the matched text.
     *
     * <p>It is equivalent to {@code yytext().charAt(pos)}, but faster.
     *
     * @param position the position of the character to fetch. A value from 0 to {@code
     *     yylength()-1}.
     * @return the character at {@code position}.
     */
    @Override
    public final char yycharat(int position) {
        return zzBuffer[zzStartRead + position];
    }

    /**
     * How many characters were matched.
     *
     * @return the length of the matched text region.
     */
    @Override
    public final int yylength() {
        return zzMarkedPos - zzStartRead;
    }

    /**
     * Reports an error that occurred while scanning.
     *
     * <p>In a well-formed scanner (no or only correct usage of {@code yypushback(int)} and a
     * match-all fallback rule) this method will only be called with things that "Can't Possibly
     * Happen".
     *
     * <p>If this method is called, something is seriously wrong (e.g. a JFlex bug producing a
     * faulty scanner etc.).
     *
     * <p>Usual syntax/scanner level error handling should be done in error fallback rules.
     *
     * @param errorCode the code of the error message to display.
     */
    private static void zzScanError(int errorCode) {
        String message;
        try {
            message = ZZ_ERROR_MSG[errorCode];
        } catch (ArrayIndexOutOfBoundsException e) {
            message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
        }
        throw new Error(message);
    }

    /**
     * Pushes the specified amount of characters back into the input stream.
     *
     * <p>They will be read again by then next call of the scanning method.
     *
     * @param number the number of characters to be read again. This number must not be greater than
     *     {@link #yylength()}.
     */
    @Override
    public void yypushback(int number) {
        if (number > yylength()) zzScanError(ZZ_PUSHBACK_2BIG);
        zzMarkedPos -= number;
    }

    /**
     * Resumes scanning until the next regular expression is matched, the end of input is
     * encountered or an I/O-Error occurs.
     *
     * @return the next token.
     */
    @SuppressWarnings("fallthrough")
    public Token yylex() {
        int zzInput;
        int zzAction;
        // cached fields:
        int zzCurrentPosL;
        int zzMarkedPosL;
        int zzEndReadL = zzEndRead;
        char[] zzBufferL = zzBuffer;
        int[] zzTransL = ZZ_TRANS;
        int[] zzRowMapL = ZZ_ROWMAP;
        int[] zzAttrL = ZZ_ATTRIBUTE;
        while (true) {
            zzMarkedPosL = zzMarkedPos;
            zzAction = -1;
            zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
            zzState = ZZ_LEXSTATE[zzLexicalState];
            // set up zzAction for empty match case:
            int zzAttributes = zzAttrL[zzState];
            if ((zzAttributes & 1) == 1) {
                zzAction = zzState;
            }
            zzForAction:
            {
                while (true) {
                    if (zzCurrentPosL < zzEndReadL) {
                        zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
                        zzCurrentPosL += Character.charCount(zzInput);
                    } else if (zzAtEOF) {
                        zzInput = YYEOF;
                        break zzForAction;
                    } else {
                        // store back cached positions
                        zzCurrentPos = zzCurrentPosL;
                        zzMarkedPos = zzMarkedPosL;
                        boolean eof = zzRefill();
                        // get translated positions and possibly new buffer
                        zzCurrentPosL = zzCurrentPos;
                        zzMarkedPosL = zzMarkedPos;
                        zzBufferL = zzBuffer;
                        zzEndReadL = zzEndRead;
                        if (eof) {
                            zzInput = YYEOF;
                            break zzForAction;
                        } else {
                            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
                            zzCurrentPosL += Character.charCount(zzInput);
                        }
                    }
                    int zzNext = zzTransL[zzRowMapL[zzState] + zzCMap(zzInput)];
                    if (zzNext == -1) break zzForAction;
                    zzState = zzNext;
                    zzAttributes = zzAttrL[zzState];
                    if ((zzAttributes & 1) == 1) {
                        zzAction = zzState;
                        zzMarkedPosL = zzCurrentPosL;
                        if ((zzAttributes & 8) == 8) break zzForAction;
                    }
                }
            }
            // store back cached position
            zzMarkedPos = zzMarkedPosL;
            if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
                zzAtEOF = true;
                switch (zzLexicalState) {
                    case YYINITIAL:
                        {
                            addEndToken(INTERNAL_HEADER_NAME);
                            return firstToken;
                        }
                        // fall though
                    case 54:
                        break;
                    case HEADER_NAME:
                        {
                            if (zzStartRead == zzEndRead) {
                                addEndToken(bodySignal);
                            } else {
                                addEndToken(headerNameType());
                            }
                            return firstToken;
                        }
                        // fall though
                    case 55:
                        break;
                    case HEADER_NAME_CONTENT_TYPE:
                        {
                            addEndToken(headerNameType());
                            return firstToken;
                        }
                        // fall though
                    case 56:
                        break;
                    case HEADER_VALUE:
                        {
                            addEndToken(headerNameType());
                            return firstToken;
                        }
                        // fall though
                    case 57:
                        break;
                    case HEADER_VALUE_CONTENT_TYPE:
                        {
                            addEndToken(headerNameType());
                            return firstToken;
                        }
                        // fall though
                    case 58:
                        break;
                    default:
                        return null;
                }
            } else {
                switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
                    case 1:
                        {
                            addToken(Token.FUNCTION);
                        }
                        // fall through
                    case 11:
                        break;
                    case 2:
                        {
                            addToken(Token.WHITESPACE);
                        }
                        // fall through
                    case 12:
                        break;
                    case 3:
                        {
                            addToken(Token.DATA_TYPE);
                        }
                        // fall through
                    case 13:
                        break;
                    case 4:
                        {
                            addToken(Token.SEPARATOR);
                            yybegin(HEADER_VALUE);
                        }
                        // fall through
                    case 14:
                        break;
                    case 5:
                        {
                            String name =
                                    new String(zzBuffer, zzStartRead, zzMarkedPos - zzStartRead);
                            addToken(Token.DATA_TYPE);
                            if (name.equalsIgnoreCase("Content-Type")) {
                                yybegin(HEADER_NAME_CONTENT_TYPE);
                            }
                        }
                        // fall through
                    case 15:
                        break;
                    case 6:
                        {
                            addToken(Token.SEPARATOR);
                            yybegin(HEADER_VALUE_CONTENT_TYPE);
                        }
                        // fall through
                    case 16:
                        break;
                    case 7:
                        {
                            addToken(Token.LITERAL_CHAR);
                        }
                        // fall through
                    case 17:
                        break;
                    case 8:
                        {
                            String value =
                                    new String(zzBuffer, zzStartRead, zzMarkedPos - zzStartRead);
                            addToken(Token.LITERAL_CHAR);
                            if (value.regionMatches(
                                    true, 0, "application/x-www-form-urlencoded", 0, 33)) {
                                bodySignal = SIGNAL_BODY_FORM;
                            } else if (value.regionMatches(true, 0, "application/json", 0, 16)) {
                                bodySignal = SIGNAL_BODY_JSON;
                            }
                        }
                        // fall through
                    case 18:
                        break;
                    case 9:
                        // lookahead expression with fixed lookahead length
                        zzMarkedPos =
                                Character.offsetByCodePoints(
                                        zzBufferL,
                                        zzStartRead,
                                        zzEndRead - zzStartRead,
                                        zzMarkedPos,
                                        -1);
                        {
                            addToken(Token.RESERVED_WORD);
                        }
                        // fall through
                    case 19:
                        break;
                    case 10:
                        {
                            addToken(Token.LITERAL_STRING_DOUBLE_QUOTE);
                        }
                        // fall through
                    case 20:
                        break;
                    default:
                        zzScanError(ZZ_NO_MATCH);
                }
            }
        }
    }

    public HttpRequestHeaderTokenMaker() {}
}
