# syntax=docker/dockerfile:1
# This dockerfile builds a ZAP docker image used for integration tests

# This code uses a specific and immutable builder image from the debian SHA256 digest, making it pinned to digests rather than floating tags. This allows us to change the digest explicitly when you choose to bump the base, instead of silently whenever Debian updates the tag.
FROM --platform=linux/amd64 debian@sha256:<debian_bookworm_slim_digest> AS builder

ARG DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -q -y --fix-missing \
	openjdk-17-jdk \
	git && \
	rm -rf /var/lib/apt/lists/* && \
	mkdir /zap-src

WORKDIR /zap-src

# Build required add-ons
RUN git clone --depth 1 https://github.com/zaproxy/zap-extensions.git && \
	cd zap-extensions && \
	./gradlew :aO:dev:cZAO --into /zap-src/zap/plugin/

# Pinned ZAP nightly base image, allowing us to buil "from nightly" and freeze a speficic nightly via its digest, create a test image that won't randomly change even if a new nightly is pushed, and consuming a newer nightly required explicit update of <zaproxy_nightly_digest>
FROM ghcr.io/zaproxy/zaproxy@sha256:<zaproxy_nightly_digest>
LABEL maintainer="psiinon@gmail.com"

ARG DEBIAN_FRONTEND=noninteractive

#Change to the zap user so things get done as the right person (apart from copy)
USER zap

COPY --link --from=builder --chown=1000:1000 /zap-src/zap/plugin/* /home/zap/.ZAP_D/plugin/

COPY --link --chown=1000:1000 integration_tests /zap/wrk/

# Pick up any local changes
COPY --link --chown=1000:1000 zap* CHANGELOG.md /zap/

RUN chmod +x /zap/wrk/*.sh

WORKDIR /zap
