# syntax=docker/dockerfile:1
# This dockerfile builds the zap bare release
FROM --platform=linux/amd64 debian:bullseye-slim AS builder

RUN apt-get update && apt-get install -q -y --fix-missing \
	wget \
	curl \
	openjdk-11-jdk \
	xmlstarlet \
	unzip && \
	apt-get clean

WORKDIR /zap

# Download and expand the latest stable release
RUN wget -qO- https://raw.githubusercontent.com/zaproxy/zap-admin/master/ZapVersions.xml | xmlstarlet sel -t -v //url |grep -i Linux | wget --content-disposition -i - -O - | tar zxv && \
	mv ZAP*/* . && \
	rm -R ZAP*

# Update add-ons
RUN ./zap.sh -cmd -silent -addonupdate
# Copy them to installation directory
RUN cp /root/.ZAP/plugin/*.zap plugin/ || :

FROM eclipse-temurin:11-jre-alpine AS final
LABEL maintainer="psiinon@gmail.com"

RUN apk update && apk add bash curl 

USER root

WORKDIR /zap
COPY --from=builder --link --chown=1337:1337 /zap .
COPY --link --chown=1337:1337 policies /home/zap/.ZAP/policies/

RUN echo "zap2docker-bare" > /zap/container

RUN /usr/sbin/adduser -u 1337 -h /home/zap -s /bin/bash -D zap && \
    rm -rf /var/cache/apk/*

#Change to the zap user so things get done as the right person (apart from copy)
USER zap

ENV PATH $JAVA_HOME/bin:/zap/:$PATH
ENV ZAP_PATH /zap/zap.sh
ENV HOME /home/zap/
ENV ZAP_PORT 8080

HEALTHCHECK CMD curl --silent --output /dev/null --fail http://localhost:$ZAP_PORT/ || exit 1
